# Generated by Django 5.2.1 on 2025-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='download_count',
            new_name='downloads',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='parent_patch',
        ),
        migrations.AddField(
            model_name='patch',
            name='forks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patch',
            name='synth_type',
            field=models.CharField(default='basic', max_length=50),
        ),
    ]
