# Generated by Django 5.2.1 on 2025-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0003_patch_parent_alter_patch_synth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='duration',
            field=models.CharField(default='8n', max_length=10),
        ),
        migrations.AddField(
            model_name='patch',
            name='note',
            field=models.CharField(default='C4', max_length=10),
        ),
    ]
