# Generated by Django 5.2.1 on 2025-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0004_patch_duration_patch_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
