# Generated by Django 5.2.1 on 2025-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0005_patch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
