# Generated by Django 5.2.1 on 2025-07-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0006_patch_is_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='patch',
            name='parent',
        ),
        migrations.AddField(
            model_name='patch',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='synthpatches.patch'),
        ),
        migrations.AddField(
            model_name='patch',
            name='stem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offshoots', to='synthpatches.patch'),
        ),
        migrations.AddField(
            model_name='patch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='version',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='patch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
