# Generated by Django 5.2.1 on 2025-07-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0007_alter_patch_options_remove_patch_parent_patch_root_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={},
        ),
        migrations.AddField(
            model_name='patch',
            name='immediate_predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_successors', to='synthpatches.patch'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='synthpatches.patch'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='stem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks_from', to='synthpatches.patch'),
        ),
    ]
