# Generated by Django 5.2.1 on 2025-09-30 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0008_alter_patch_options_patch_immediate_predecessor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('bpm', models.PositiveIntegerField(default=120)),
                ('time_signature', models.CharField(default='4/4', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(blank=True, default='0.0', max_length=20)),
                ('is_posted', models.BooleanField(default=False)),
                ('immediate_predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_direct_successors', to='synthpatches.track')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_descendants', to='synthpatches.track')),
                ('stem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_forks_from', to='synthpatches.track')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('patch_snapshot', models.JSONField()),
                ('steps', models.JSONField(default=list)),
                ('note', models.CharField(default='C4', max_length=10)),
                ('duration', models.CharField(default='8n', max_length=10)),
                ('gain', models.FloatField(default=1.0)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='synthpatches.patch')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='synthpatches.track')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
