# Generated by Django 5.2.1 on 2025-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0009_alter_patch_options_track_trackitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackitem',
            options={'ordering': ['order_index', 'start_beat', 'id']},
        ),
        migrations.RenameField(
            model_name='trackitem',
            old_name='gain',
            new_name='length_beats',
        ),
        migrations.RemoveField(
            model_name='trackitem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trackitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='trackitem',
            name='steps',
        ),
        migrations.AddField(
            model_name='trackitem',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trackitem',
            name='start_beat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='trackitem',
            index=models.Index(fields=['track', 'order_index', 'start_beat'], name='synthpatche_track_i_76a69e_idx'),
        ),
    ]
