# Generated by Django 5.2.1 on 2025-10-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0011_savedtrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='time_signature',
        ),
    ]
