# Generated by Django 5.2.1 on 2025-10-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0012_remove_track_time_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackitem',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='trackitem',
            name='track',
        ),
        migrations.AddField(
            model_name='track',
            name='composition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='SavedTrack',
        ),
        migrations.DeleteModel(
            name='TrackItem',
        ),
    ]
