# Generated by Django 5.2.1 on 2025-11-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0013_remove_trackitem_patch_remove_trackitem_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='note',
        ),
    ]
