# Generated by Django 5.2.1 on 2025-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthpatches', '0014_remove_patch_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
